version: '3'
services:
  web:
    build: ./app
    container_name: app
    ports: 4500:4500
    volumes:
      - ./app:/usr/src/app

  api:
    build: ./api
    container_name: api
    ports: 4500:4500
    volumes:
      - ./app:/usr/src/app
      depends_on: mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes: ./data/db:/data/db
    ports: 27017:27017
