version: '2'
services:
  app:
    build: .
    container_name: app
    ports:
      - "4501:4501"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/rws
    environment:
      - MONGO_URL=mongodb://mongodb/react-store
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=react-store
